Try using format function

diff --git a/.github/workflows/verify-success.yml b/.github/workflows/verify-success.yml
--- a/.github/workflows/verify-success.yml
+++ b/.github/workflows/verify-success.yml
@@ -33,7 +33,7 @@ jobs:
       - name: Check for cancelled jobs
         # if: ${{ inputs.fail_if_cancelled && contains(env.NEEDS_RESULT, 'cancelled') }}
         # run: echo "$MESSAGE_PREFIX$MESSAGE" && exit $EXIT_CODE
-        run: echo "${{ env.MESSAGE_PREFIX}}${{ env.MESSAGE}}" && exit ${{ env.EXIT_CODE}}
+        run: echo "${{ format('{0}{1}', inputs.fail_if_cancelled && env.RESULT && '::error ::' || '',  env.MESSAGE) }}" && echo "${{ env.MESSAGE_PREFIX}}${{ env.MESSAGE}}" && exit ${{ env.EXIT_CODE}}
         env:
           RESULT: ${{ contains(env.NEEDS_RESULT, 'cancelled') }}
           MESSAGE: ${{ contains(env.NEEDS_RESULT, 'cancelled')  && 'Some jobs were cancelled' || 'No jobs were cancelled' }}
