Set ::error workflow command

diff --git a/.github/workflows/verify-success.yml b/.github/workflows/verify-success.yml
--- a/.github/workflows/verify-success.yml
+++ b/.github/workflows/verify-success.yml
@@ -25,13 +25,13 @@ jobs:
         run: echo "::error Some jobs failed" && exit 1
       - name: Check for cancelled jobs
         if: ${{ contains(env.NEEDS_RESULT, 'cancelled') }}
-        run: echo "Some jobs were cancelled" && exit 1
+        run: echo "::error Some jobs were cancelled" && exit 1
       - name: Check for skipped jobs
         if: ${{ contains(env.NEEDS_RESULT, 'skipped') }}
-        run: echo "Some jobs were skipped" && exit 1
+        run: echo "::error Some jobs were skipped" && exit 1
       - name: Check for successful jobs
         if: ${{ !contains(env.NEEDS_RESULT, 'success') }}
-        run: echo "No job results were successful" && exit 1
+        run: echo "::error No job results were successful" && exit 1
       - run: echo "Checks passed successfully"
         if: ${{ success() }}
       - run: echo "Checks failed"
